name: venv
channels: 
 - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - nco
  - pynco 
  - dask
  - requests
  - xarray
  - netcdf4
  - h5py
  - python-dotenv
  - scipy
  - schedule
  - pip:
    - climate-indices
