name: venv
channels: 
 - conda-forge
dependencies:
  - python=3.12.2
  - pip
  - pandas
  - numpy
  - nco
  - pynco 
  - dask
  - netCDF4=1.6.2
  - requests
  - xarray
  - h5py
#prefix: ./EHCPA_SPI/venv1P